/*
 Navicat Premium Data Transfer

 Source Server         : local_mysql
 Source Server Type    : MySQL
 Source Server Version : 50620
 Source Host           : localhost:3306
 Source Schema         : laravel_course_job

 Target Server Type    : MySQL
 Target Server Version : 50620
 File Encoding         : 65001

 Date: 03/08/2019 10:41:50
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for jobs
-- ----------------------------
DROP TABLE IF EXISTS `jobs`;
CREATE TABLE `jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `company_id` int(11) NOT NULL,
  `category_id` int(11) NOT NULL,
  `job_title` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `job_type` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `city_id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `region_id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `due_date` date NOT NULL,
  `status` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `number_of_vacancy` int(11) NOT NULL,
  `experience` int(11) NOT NULL,
  `gender` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `salary` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of jobs
-- ----------------------------
BEGIN;
INSERT INTO `jobs` VALUES (1, 171, 101, 4, 'web-developer', 'fulltime', 'private-household-cook', 'REQUIREMENTS: \nMinimum 5 years of system analysis and application development supplemented by a post secondary IT degree/diploma. \nExperience in object-oriented software application development and design.\nBroad knowledge of computer systems technology, programming and design techniques.\nStrong programming skills in .NET (C#), Web Services. \nExperience with application development using SQL.\nExperience with development methodologies is an asset.\nExcellent communications skills required.', '71567 Balistreri Turnpike\nNorth Dejah, WA 06521-8614', '52270 Von Mount Apt. 288\nCarolinatown, MN 01483', '1971-10-14', 1, '2019-04-16 20:13:25', '2019-04-16 20:13:25', 10, 5, 'female', '9218');
INSERT INTO `jobs` VALUES (2, 173, 102, 4, 'Web Developer', 'fulltime', 'telephone-station-installer-and-repairer', 'Bachelor of Science degree in Computer Science or equivalent\nFive (5) plus years experience working as a Web Developer \nProficient with HTML, CSS, and JavaScript\nOne (1) year of experience working with E-Commerce\nMust possess strong communication skills and the ability to work on multiple projects at once\nGood interpersonal, organizational and analytical skills\nAbility to work in an agile, fast paced environment ', '6604 Annalise Walk\nGarnethaven, CO 20267-1336', '67349 Timmothy Crest\nMayertburgh, SC 04734-9697', '1973-09-26', 0, '2019-07-12 14:03:54', '2019-07-12 14:03:54', 9, 3, 'male', '11636');
INSERT INTO `jobs` VALUES (5, 179, 105, 5, 'Business Management', 'fulltime', 'occupational-therapist', 'We’re looking for passionate Business Leaders or Writers to work online answering advanced engineering questions sent from students all over the world. As a contract Business Management Expert, you\'ll receive the following:\n\nReliable Payments: Timely, reliable payments twice a month\nIndependence: No waiting, no assignments, and a massive library of questions for you to choose from\nFlexibility: Work from anywhere, at any time, completely online\nSupportive Staff: Access to a supportive in-house team to answer your questions\nWhat we’re looking for:\n\nExpertise in advanced topics in Business Management\nStrong English-language Reading and Writing skills', '67003 Lacy Curve\nScotville, SC 76401-7403', '921 Schneider Turnpike\nSouth Donniestad, OK 62224-9919', '1979-02-28', 1, '2019-02-19 05:04:21', '2019-02-19 05:04:21', 6, 5, 'male', '14065');
INSERT INTO `jobs` VALUES (7, 183, 107, 1, 'Water Resources Engineer', 'fulltime', 'order-filler', 'The successful candidate will also have:\n\n* A current P.Eng or E.I.T. designation with Professional Engineers Ontario.\n* Familiarization with CAD software (AutoCAD Civil 3D or MicroStation).\n* Familiarization with construction inspection and administration.\n* Experience preparing written reports (SWMR, FSR, Design Briefs).\n* Expert knowledge of industry-standard hydrologic and hydraulic modelling software packages.\n* Expert knowledge of municipal sewer design in accordance with local policies and procedures.\n* Extensive knowledge of local municipal, provincial and conservation authority policies and regulations, specifications and approvals process.\n* Extensive knowledge of local municipality standards, specifications, tendering and approvals process.', '46694 Kessler Via Suite 118\nWest Josuetown, NJ 47020', '2802 Aurore Via Suite 896\nJanniehaven, GA 81562-4805', '2013-11-25', 0, '2019-06-12 18:38:58', '2019-06-12 18:38:58', 9, 1, 'male', '19296');
INSERT INTO `jobs` VALUES (8, 185, 108, 3, 'IT Helpdesk Technician', 'parttime', 'sales-representative', 'Demonstrated interest in IT troubleshooting, providing a better solution, and self improvement Experience working in a fast paced, results driven environment Proven track record of excellent customer service in 500+ users environments Familiarity with MacOS, iOS, GSuite, Windows, Box, Imaging/deployment, network printers Solid troubleshooting and research skills across multi platform desktop and networking issues Excellent communication and interpersonal skills and a positive attitude are a must Ability to respond to rapidly changing priorities, tight timelines, and a fast-paced environment Experience in imaging MacOS and Windows systems', '226 Berge Junctions\nNew Sheaborough, MN 67815', '65151 Salvatore Circles Apt. 349\nAlexaneton, RI 95446-5442', '1978-09-02', 0, '2019-07-26 02:06:09', '2019-07-26 02:06:09', 9, 5, 'female', '14149');
INSERT INTO `jobs` VALUES (11, 191, 111, 4, 'Financial Analyst', 'fulltime', 'professor', 'The qualified candidate must have:\nA Bachelor\'s Degree or equivalent work experience in IT and/or business administration. Finance accountancy/ finance degree preferable;\nFive plus (5+) years of Project/Financial Analyst experience in complex projects with direct support responsibilities to project/program manager(s);\nExperience supporting the management of project financials (budget, forecast, variance) of at least $1M;\nExperience working within Health Authorities;\nAnalytical skills including the ability to comprehend, analyze, and resolve complex issues and present information in concise meaningful ways;\nDemonstrated ability to use database, spreadsheet and word processing software at an advanced level. MS Office Suite products, particularly MS PowerPoint and MS Excel (Knowledge with Macros/Pivot tables, SUM_IF, IF_THEN, VLOOKUP);\nWorking knowledge of projects and various reporting/analytical tools;\nDemonstrated understanding of the Project Delivery Life Cycle;\nExperience working in a project environment involving PMO and multiple stakeholder(s);\nThe ability to work effectively as part of a team;\nThe ability to work independently with minimal supervision;\nHighly developed business writing and verbal communication skills with the ability to document work appropriately, including executive briefing notes;\nDemonstrated ability to exercise tact, good judgment, and initiative; and,\nMainstream project management software/tools experience preferred.', '312 May Trafficway\nNew Terrill, OR 47112-0411', '4639 Kreiger Fields\nSouth Jaylan, NJ 56961', '1977-12-12', 0, '2019-06-27 14:31:56', '2019-06-27 14:31:56', 6, 8, 'female', '16541');
INSERT INTO `jobs` VALUES (12, 193, 112, 4, 'Call Center Manager', 'fulltime', 'plasterer-or-stucco-mason', 'Hire, train and onboard new Call Center Agents as required to meet quotas\nProvide coaching and assistance to call center agents on an ongoing basis\nProcess weekly sales leads reports for submission to management\nOversee and ensure conflict resolution between associates and customers\nEnsure that all employees follow the company’s best practices for call center management and operations\nDevelop presentations and talks to motivate and educate call center agents\nCommunicate company goals to associates so every employee understands his or her role\nConduct periodic surveys of customers and potential customers to ensure quality control', '6359 Spinka Way\nConsidinechester, WI 03475-1078', '64866 Devon Lights\nBusterton, IA 35171-4238', '1986-01-12', 1, '2019-05-17 04:41:29', '2019-05-17 04:41:29', 9, 3, 'female', '10876');
INSERT INTO `jobs` VALUES (15, 199, 115, 5, 'Office Clerk - Billing', 'fulltime', 'mining-engineer-or-geological-engineer', 'your responsibilities \n\nFilling\nData entry - billing\nPerform other related clerical tasks\nour offer\n\nTemporary employment for an indefinite period\nSchedule from Monday to Friday 8:00-5:00\n$16/hour\nEntry into office as of Tuesday June 18th\nLocation in Dorval\nour expectations\n\nExperience in an administrative role\nGood computer skills\nWorks well and efficiently\nThorough', '836 Dereck Way\nDouglasland, SD 85577-6582', '161 Kuhn Ports\nWilfridtown, DC 95311-8370', '1992-07-22', 0, '2019-07-30 17:41:12', '2019-07-30 17:41:12', 5, 7, 'male', '18044');
INSERT INTO `jobs` VALUES (16, 201, 116, 5, 'Full Stack Web Developer ', 'fulltime', 'stock-clerk', 'Programming Languages / Protocols / Frameworks (5+ years):\nHTML5\nCSS3 and Sass\nJavaScript\njQuery and promises\nJSON\nHTTP/HTTPS REST\nCORS\nOAuth2\nsessionStorage, localStorage, indexedDB\nAngular\nBootstrap\n.Net Core\nC#\nFull stack development implementing web, distributed and service-oriented architectures and technologies', '75921 Camron Unions\nWest Roger, ME 72288', '14499 Schneider Point Suite 803\nSouth Isabellton, OK 76805', '1981-01-09', 1, '2019-04-06 15:24:36', '2019-04-06 15:24:36', 8, 7, 'male', '7054');
INSERT INTO `jobs` VALUES (17, 203, 117, 2, 'Low Level Software Developer', 'contract', 'secretary', 'Responsibilities:\n-Develop software drivers for various hardware peripherals including adaptation of existing drivers\n-Examples of hardware peripherals requiring drivers: Ethernet, USB, Serial (UART, QUAD SPI, I2C), PCIe, eMMC, DSI MiPi,  etc.\n-Enhancement of existing board support packages\n-Bring up of new in-house developed HW modules\n-Development of new driver architectures to support future hardware peripheral advancements\n-Test and debug BSP SW as required to ensure code is passing quality standards\n-Extend existing SW architecture for new features', '35194 Macejkovic Isle Apt. 049\nPort Jonathon, AL 30442-3595', '83050 Stanton Fall Suite 367\nMosciskimouth, WI 10406-1355', '1978-10-07', 1, '2019-03-30 02:34:03', '2019-03-30 02:34:03', 7, 7, 'female', '17003');
INSERT INTO `jobs` VALUES (19, 207, 119, 3, 'Account Manager', 'fulltime', 'pump-operators', 'Job Requirements\nGrow existing staffing clients and develop new staffing clients\nTrack all job requisitions and candidates\nCalibrate candidates and client update meetings with managers and upper management\nConduct interviews; reference checks and orientations\nAssist with on-boarding, orientations, and kickoffs\nEnsure completion of all candidate employment documentation\nIdentify, utilize and track recruitment and advertising sources and methods\nBuild positive, credible relationships with customers\nLiaise with employees and clients\nMonitor employee performance\nCreate daily, weekly and monthly reports\nDevelop a pipeline of candidates ready to join\nPerform other duties as assigned', '160 Giuseppe Ports Apt. 101\nChelseaberg, OH 18581-9842', '82513 Witting Views\nLake Curt, WY 86879-6180', '2006-01-22', 0, '2019-03-12 22:55:01', '2019-03-12 22:55:01', 8, 2, 'female', '9666');
INSERT INTO `jobs` VALUES (20, 209, 120, 2, 'Front End Web Developer', 'contract', 'transportation-inspector', '- Strong knowledge of the latest standards and techniques of HTML, CSS, JavaScript/jQuery. (nice to Angular)\n- Basic understanding of server-side CSS pre-processing platforms, such as LESS and SASS, Bourbon/Neat.\n- Experience working with CMS (preferably OpenText WEM)', '959 Mitchell Station Apt. 006\nPort Ike, ME 54329-2782', '110 Maverick Underpass\nJoaquinland, WA 55022-6880', '2006-06-11', 1, '2019-06-26 20:04:01', '2019-06-26 20:04:01', 4, 8, 'female', '13485');
INSERT INTO `jobs` VALUES (21, 211, 121, 3, 'District Sales Manager', 'fulltime', 'parking-lot-attendant', 'Bachelor’s Degree in Business Information Systems, Marketing, Communications or similar field or equivalent work experience required.\n10 + years sales experience\nPrevious experience in telecom, call center, software or hardware industries\nHighly professional demeanor - presence, voice\nDemonstrated high level competency in written and verbal communications\nDemonstrated success working with little to no direct daily supervision in a home office setting', '86950 Blaise Green Suite 706\nWilkinsonview, CO 09380-0743', '7262 Ted Overpass Apt. 334\nLucybury, SC 01562', '1992-02-20', 0, '2019-07-03 17:11:28', '2019-07-03 17:11:28', 10, 7, 'female', '13142');
INSERT INTO `jobs` VALUES (22, 213, 122, 1, 'Senior Internal Auditor', 'fulltime', 'public-relations-specialist', '3+ years of financial and risk based auditing experience, including a good understanding of risks and controls\nChartered Professional Accounting (CPA) designation\nCurrent knowledge of audit industry best practices\nWillingness to travel occasionally, within North America\nWhat we would love to see?\n\nDemonstrated strong communication, negotiation and conflict resolution abilities\nExcellent analytical, problem solving skills and writing skills\nAbility to adapt to change quickly, multi-task, set priorities and plan appropriately\nComfortable around senior management, can maintain composure in challenging situations and has the interpersonal savvy to deal with all levels in the organization\nPublic company or software/technology industry experience\nFinancial systems knowledge and familiarity; Great Plains or Blackline experience an asset but not essential\nPublic company experience, particularly in the Software or Technology sector', '94214 Benedict Shoal\nElissaberg, IL 10435', '199 Jacynthe Pass\nHamilltown, KS 62646-1935', '1999-11-29', 0, '2019-06-08 09:19:26', '2019-06-08 09:19:26', 8, 8, 'male', '14468');
INSERT INTO `jobs` VALUES (25, 219, 125, 3, 'Continuous Improvement Lead', 'fulltime', 'nuclear-engineer', 'Duties:\n\n Key Accountabilities\n\n The lead will work with the Manager of Continuous Improvement to ensure:\n CI is embedded in every area of the business\n Identify areas for transformation based on analytics and lead large scale standardization and continuous improvement initiatives\n Tangible and sustainable benefits are realized and reported\n There is a focus on employee buy-in, motivation and behaviour change to support and realize the implementation of CI principles\n Employees are empowered with the required skills for a self-sustainable CI culture\n Action plans are followed up and reported on', '79267 Aaron Dam\nWest Tressie, VT 32615', '973 Marisa Lodge\nEast Clair, SD 48555-6412', '1991-03-18', 0, '2019-02-14 06:10:02', '2019-02-14 06:10:02', 5, 9, 'male', '12755');
INSERT INTO `jobs` VALUES (29, 227, 129, 2, 'HR Generalist', 'fulltime', 'mechanical-drafter', 'Roles and Responsibilities\n\nDay to day admin support of employee data\nFirst point of contact for employee HR inquires\nCoordinating on boarding, terminations, extended absences etc.\nPrepares, delivers and follows up on approved offer letters and onboarding documents\nCoaches leaders on basic to moderate employee relations matters. Elevates more complex matters to supervisor further support and or resolution as required\nCoordinates vacation and extended absences administration including tracking, reconciliation and fulfillment follow-up\nAssists with other HR administrative matters such as HR metrics, employment verification letters, HRIS troubleshooting and administration\nMay travel to stores on day, evening, overnight and weekends to build relationships and support HR matters (5-10% travel)\nSupports urgent evening and weekend retail HR support needs in an accurate and timely manner as required', '286 Dean Summit\nSouth Chaimchester, FL 55739', '146 Lakin Lock Apt. 253\nSimonebury, RI 24455-5614', '1978-09-29', 0, '2019-05-21 18:08:23', '2019-05-21 18:08:23', 2, 7, 'male', '8961');
INSERT INTO `jobs` VALUES (30, 229, 130, 3, 'Office Manager ', 'fulltime', 'orthotist-or-prosthetist', '5+ years in a similar office management and/or administrative role, in a small office environment, ideally within a trade association (or similar organization – i.e. regulatory body, non-profit, etc.)\n\nExperience providing administrative support to a board of directors and board committees\n\nExperience preparing professional communications, with excellent English writing skills\n\nFunctional bilingualism in English/French is strongly preferred (strong proficiency speaking and reading French, and writing English)\n\nBasic accounting support experience (accounts receivable or collections experience preferred) and/or bookkeeping experience\n\nStrong proficiency with Microsoft Office Suite including Word, Excel and Outlook; and also, with Adobe Acrobat and DropBox', '54438 Corwin Place Suite 110\nWest Berniece, NC 71433-9992', '5623 Ryleigh Ranch Suite 514\nLefflermouth, VA 01629', '2002-06-06', 1, '2019-07-08 10:33:24', '2019-07-08 10:33:24', 2, 6, 'male', '16055');
INSERT INTO `jobs` VALUES (31, 231, 131, 2, 'Civil Engineer', 'fulltime', 'physician-assistant', 'Bachelor’s Degree in Civil Engineering\n10+ years’ civil engineering experience\nSE licence highly desirable\nExtensive AutoCAD experience\nHighly developed team management and leadership skills\nWorking knowledge of HydroCAD modelling', '504 Dana Crescent Apt. 811\nEthelynview, TX 71564', '8627 Wilderman Street Suite 695\nNew Rafael, OH 64171-5700', '1976-04-08', 1, '2019-07-31 21:12:16', '2019-07-31 21:12:16', 2, 7, 'male', '9665');
INSERT INTO `jobs` VALUES (32, 233, 132, 5, 'Software Developer ', 'fulltime', 'securities-sales-agent', 'Responsibilities\n-Explore and propose various system optimizations to improve software performance.\n-Implement said optimizations where necessary/applicable.\n-Investigate and resolve complex system software issues. Interface with many functional teams from Kernel to application domains as part of the investigations.\n-Investigate system and process crashes using developed tools.\n-Perform initial triage to identify the offending component responsible for final resolution, and/or root cause where required.\n-Characterize and measure performance impacts of key feature submissions.\n\nQualifications\n-Bachelor or Masters degree or equivalent experience in Electrical/Computer Engineering, Computer Science or related field\n-5+ years’ professional experience in an embedded SW\n-Have a keen interest in software technologies, with emphasis on embedded systems design and optimization\n-High level of knowledge in C++ programming\n-Familiarity with gdb\n-Strong analytical and problem solving skills\n-Passion for improving system software performance\n-Strong communication and interpersonal skills\n\nAdditional Assets\n-Previous experience with QNX and/or Linux OS development\n-Development experience with infotainment and/or networking systems (CAN/Ethernet)\n-Experience with code repository and versioning tools such as Git', '9402 Raynor Highway\nOlsonchester, HI 93700', '50569 Clementina Land Suite 395\nPaucekville, IA 69645', '1997-06-26', 0, '2019-04-07 11:45:50', '2019-04-07 11:45:50', 2, 4, 'female', '8091');
INSERT INTO `jobs` VALUES (33, 235, 133, 3, 'Travel consulting agent', 'fulltime', 'park-naturalist', 'Advantages\n• Competitive salary\n• Benefits Program\n• Paid extensive training\n• Easily accessible by public transportation (Downtown Montreal)\n• Dynamic environment\n• Welcoming culture for new employees\n• Fast-paced, dynamic environment\n• Company acknowledges employee achievements\n• Free coffee onsite \n• Casual dresscode (i.e. wear jeans to work every day)\n\nQualifications\n• Fully Bilingual (French / English) oral and written\n• Experience in the travel industry\n• Good knowledge of geography and airports codes\n• Have the customer service experience', '351 Hagenes Crest\nWest Elroychester, MT 20947-6853', '34865 Lehner Ports Apt. 449\nEast Dollyland, TX 55733-1816', '1999-09-09', 0, '2019-02-06 05:10:31', '2019-02-06 05:10:31', 10, 7, 'female', '9400');
INSERT INTO `jobs` VALUES (34, 237, 134, 1, 'HR Director ', 'fulltime', 'photoengraving-machine-operator', 'responsibilities:\n\nCreate and implement employee relations policies to help increase employees’ job satisfaction\nDevise a list of procedures and practices for hiring new employees and managing our staff\nEstablish an orientation procedure for onboarding new hires and training them to meet the needs of the company\nCommunicate with employees about compensation, benefits and other facets of their employment\nApprove and schedule PTO and SL based on employee need and company requirements\nRespond to questions or complaints from employees in a timely fashion\nManage all other HR department personnel', '8238 Hahn Light Apt. 305\nSatterfieldchester, VT 02557-6277', '47819 Grayson Mission Apt. 476\nWest Dorthy, TX 29196', '2000-01-22', 1, '2019-06-22 22:17:52', '2019-06-22 22:17:52', 3, 2, 'female', '10695');
INSERT INTO `jobs` VALUES (35, 239, 135, 3, 'Senior Software Developer', 'fulltime', 'soil-scientist-or-plant-scientist', 'Major Responsibilities\n* Responsible for developing, maintaining and support of process application programs and related control systems * Conducts root cause analysis and troubleshoots programming issues * Adheres to our established change control management process * Encodes project requirements by converting work flow information into programming language * Responsible for system design and specifications * Adheres to all IT Policies and develops in accordance with the Magna IT Security Policy * Work closely with customers/users to develop and understand requirements and business objectives * Manage business plan projects * Ability to work extended hours when required * Other duties as required\n\nKnowledge and Education\n* University/College Degree or Diploma (preferably in Computer Science) or equivalent experience * Progressive knowledge of state of the art technologies * Proven programming ability in various languages required', '591 Hane Pines\nEast Justina, NV 52729', '326 Cole Corners\nBorermouth, OH 75522-5984', '1997-01-18', 0, '2019-04-02 23:26:02', '2019-04-02 23:26:02', 2, 4, 'female', '7065');
INSERT INTO `jobs` VALUES (37, 243, 137, 3, 'Accounts Payable', 'fulltime', 'real-estate-association-manager', 'Advantages\n- Permanent position with an incredible company who takes care of their employees\n- $35,000-$45,000/yr dependent on skills and experience\n- Monday to Friday 8:30 am - 5:00 pm\n- Great benefits plan\n- RRSP plan available\n- Generous vacation time\n- Above industry standard bonus structure based on personal and company performance\n\nQualifications\n- 3+ years experience in a fast paced accounting/accounts payable role, having experience in construction is an asset \n- Diploma in Accounting\n- Must take pride in their work, have strong attention to detail, great prioritization and multi-tasking skills\n- Extremely organized and willing/open to learn new skills\n- Can handle pressure and deadlines\n- Strong with Microsoft office and comes with experience on Sage 300 \n- Very professional, presentable, outgoing and can work well with a team', '784 Gislason River\nJesseville, DE 70255-5666', '90002 Armand Road\nWest Teagan, NE 63901-7097', '1998-10-11', 0, '2019-05-30 00:22:24', '2019-05-30 00:22:24', 7, 7, 'female', '18421');
INSERT INTO `jobs` VALUES (39, 247, 139, 5, 'Front End Web Developer', 'fulltime', 'taxi-drivers-and-chauffeur', 'Responsibilities\n* Review website designs and wireframes, ensure development requirements are clear\n* Build website front-ends, intuitively optimizing for all device sizes\n* Problem solve UX, design, code, cross-browser issues, and bring to the attention of the appropriate team members\n* Constantly collaborate with the rest of the team to ensure finished products meet the business, creative, and technical requirements\n* Work independently on multiple projects, while making sure to ask for assistance when needed\n* Optimize websites for maximum performance, cross-browser compatibility\n* Constantly improve development standards, practices, building a library of reusable resources', '1548 Rodolfo Summit\nSouth Mayeshire, MT 57906', '1095 Metz Park Apt. 648\nBatzburgh, CT 24938', '1983-06-04', 0, '2019-03-23 13:14:01', '2019-03-23 13:14:01', 1, 9, 'male', '18704');
INSERT INTO `jobs` VALUES (40, 249, 140, 4, 'Administrative Assistant', 'fulltime', 'meat-packer', 'Primary Duties:\n\nVerify production assembly sheets by ensuring that heat numbers are properly allocated on production work orders\nAssist the Sales department in processing and maintaining sales orders as well as create and complete sales orders\nCreate and maintain manufacturing work orders and work order files\nAssist shop floor personnel with daily work order bookings \nProcess, maintain, receive and complete farm-out purchase orders\nMaterial issue as required\nComplete and amalgamate work order documentation\nPrepare commercial invoice and Bill of Ladings on shipments and NAFTA documents\nResponsible for purchasing/inventory monitoring of administration consumables and rentals such as uniforms, mats, office supplies, etc\nAssist with a variety of administrative functions, including creating documents and maintaining employee files\nPerform other related duties as required', '8139 Kristian Hills\nSouth Verona, CT 27139-8966', '246 Gerlach Mission\nEast Lew, MS 66074-3533', '1981-03-30', 0, '2019-05-26 16:58:03', '2019-05-26 16:58:03', 7, 2, 'male', '7275');
INSERT INTO `jobs` VALUES (45, 259, 145, 3, 'Business Administrator', 'fulltime', 'pr-manager', 'Proficiency with purchase order management, expense management and travel and meeting coordination\nExcellent math and computer skills\nDetailed planning and time-management skills\n3+ years of experience as a Business Administrator\nGreat organizational, communication and negotiation skills\nBachelor’s Degree or higher in Business Administration, accounting or related field', '239 Hauck Inlet\nNew Christopherberg, MA 39952-7228', '755 Monahan Manors Suite 047\nGleichnerport, SD 95966-9124', '1997-06-15', 0, '2019-03-13 12:30:38', '2019-03-13 12:30:38', 9, 5, 'female', '10125');
INSERT INTO `jobs` VALUES (46, 261, 146, 2, 'Financial Controller ', 'fulltime', 'mail-clerk', 'Key responsibilities: \n- Leading, managing & mentoring of staff\n- Leading and guiding the day-to-day accounting functions and transactions \n- Preparation of financial reporting for the Board & Senior Leadership Team\n- Preparation of statutory accounts, including researching technical accounting standards for compliance\n- Quality control over financial transactions & financial reporting\n- Documentation of business processes & accounting policies to maintain & strengthen internal controls\n- Management of, and compliance with, regulatory reporting requirements & tax filings\n- Management of the annual audit process\n- Continuous assessment & improvement of the effectiveness & efficiency of financial processes', '394 Felicity Islands Suite 546\nAaronburgh, MO 28795-5159', '78459 Schuster Junctions\nAmaraside, AL 78140', '1989-12-20', 0, '2019-04-30 09:20:13', '2019-04-30 09:20:13', 7, 4, 'male', '19690');
INSERT INTO `jobs` VALUES (47, 263, 147, 2, 'Consultant Income Tax', 'fulltime', 'maintenance-supervisor', 'Duties and Responsibilities:\n\nPeople:\n\nCreate a positive team member experience.\nClient:\n\nAssists Manager in preparation, completion, and understanding of accounting tax provisions.\nAssists Manager in tax research and preparation of client memorandum.\nResponds to client requests and corresponds with clients to meet deliverables, with supervision provided by Manager.\nValue:\n\nFamiliarity with Canadian compliance including Forms T2, T106, T1134, T5013, NR4, T1.\nAbility to multi-task and manage a workload across multiple clients.\nAssist in the growth of practice through the preparation of training seminars.\nPerforms other duties as assigned.', '151 Timmy Junctions\nPort Devinfort, OK 36135-4741', '8792 Buddy Drive Suite 111\nBalistrerihaven, ND 51517', '1990-09-28', 1, '2019-07-10 22:34:40', '2019-07-10 22:34:40', 1, 3, 'female', '10139');
INSERT INTO `jobs` VALUES (48, 265, 148, 4, 'Accounts Payable Clerk', 'fulltime', 'real-estate-appraiser', 'Code and enter invoices into our accounting system.\n•	Reconcile vendor statements, and issue payments within payment terms.\n•	Code all cheques to appropriate ledger accounts.\n•	Posting journal entries to maintain accounting schedules.\n•	Related administration tasks such as filing, faxing and dealing with customers.\n•	Handle receptionist duties during lunch and break coverage.\n•	Other duties as requested by management\n\nQualifications: \n\n•	2 – 3 years of experience in AR/AP and book keeping\n•	Excellent communication skills\n•	Experience in using MS Office applications – Word, Excel and Outlook as well as use various databases\n•	Excellent customer service and client support experience\n•	Experience in the same industry is a definite asset. \n•	Comfortable working in s blue collared, industrial work space\n•	Able to work in a fast paced environment', '2802 Swift Islands Suite 206\nSouth Vincefort, ID 25253', '98379 Runolfsdottir Orchard Apt. 445\nSengerborough, CT 57632-4580', '2000-03-25', 0, '2019-01-22 07:23:16', '2019-01-22 07:23:16', 7, 1, 'male', '11590');
INSERT INTO `jobs` VALUES (50, 269, 150, 5, 'Car Sales Associates', 'fulltime', 'parts-salesperson', 'Requirements:\n\nProven track record in sales             \nSelf-motivation\nSelf-starter\nExcellent communication skills (we place a lot of value on being personable and happy to help)\nStrong customer relationship-building skills\nValid Driver’s license\nAbility to think like a customer, in order to provide the best possible sales experience\nExperience in the auto industry is an asset', '27203 Collier Canyon\nNew Jordanemouth, TN 07970', '9104 Camille Coves\nNew Vadashire, NM 93401-1447', '1992-10-06', 1, '2019-07-03 10:45:20', '2019-07-03 10:45:20', 8, 4, 'male', '14603');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
